config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  resources :events, :only => [:index, :new, :create, :show]
  # get 'events/new' => 'events#new'
  # get 'events/create'
  # get 'events/:id' => 'events#show'
  # post '/events' => 'events#create'
  root :to => "events#index"
  resources :tickets
  devise_for :users
devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ActiveRecord::Base
    validates :artist, :presence => true
    validates :description, :presence => true
    validates :price_low, :presence => true, :numericality =>true
    validates :price_high, :presence => true, :numericality =>true
    validates :event_date, :presence => true

    validate :event_date_not_from_past
    validate :price_low_not_higher_than_high

    private
    def event_date_not_from_past
        if event_date < Date.today
            errors.add('Data wydarzenia', 'nie może być z przeszłości')
        end
    end

    def price_low_not_higher_than_high
        if price_high < price_low
            errors.add('Cena minimalna', 'nie moze byc wieksza niz najwieksza')
        end
    end

    has_many :tickets
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    validates :name, :presence => true, :length => { :minimum => 6 }
    validates :email_address, :presence => true, format: { with: URI::MailTo::EMAIL_REGEXP } 
    validates :price, :presence => true
    validates :address, :presence => true
    validates :seat_id_seq, :presence => true
    validates :phone, :presence => true

    belongs_to :event
    belongs_to :user

    validate :paid_in_range

    private

    def paid_in_range
        if price < event.price_low or price > event.price_high
            errors.add('Cena', 'musi byc w zasiegu')
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]
  before_action :check_logged_in, :only => [:new, :create]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    event_parmas = params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date) 
    @event = Event.new(event_parmas)
    if @event.save
      flash[:komunikat] = 'Event został poprawnie stworzony.'
      redirect_to "/events/#{@event.id}"
    else
      render 'new'
    end end

  def show
  end

  def new
    @event = Event.new
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def check_logged_in
      redirect_to events_path, notice: "Nie jesteś uprawniony" if current_user.nil? or !current_user.isAdmin 
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show] 
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  # before_action :update_ticket, only: [:create]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
    @events = Event.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit 
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.event_id = params[:ticket][:event_id]

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id, :user_id)
    end

    def correct_user
      @ticket = current_user.tickets.find_by(id: params[:id])
      redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if @ticket.nil? and !current_user.isAdmin end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
<% if @event.errors.any? %> 
 
<div id="error_explanation"> <ul>
<% @event.errors.full_messages.each do |message| %> 
<li><%= message %></li>
<% end %> </ul>
</div> <% end %>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price_low %>
    <%= form.number_field :price_low %>
  </div>

  <div class="field">
    <%= form.label :price_high %>
    <%= form.number_field :price_high %>
  </div>

  <div class="field">
    <%= form.label :event_date %>
    <%= form.date_field :event_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_new_ticket.html.erb
<%= render 'tickets/form', ticket: ticket %>

app/views/events/_tickets_list.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
        <div class="col-sm-12  mx-auto p-4">
<h1>Tickets</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Seat id seq</th>
      <th>Address</th>
      <th>Price</th>
      <th>Phone</th>
      <th>Email address</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.phone %></td>
        <td><%= ticket.email_address %></td>
        <td><%= ticket.user.email %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= button_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>

<br>

app/views/events/create.html.erb
<h1>Events#create</h1>

app/views/events/index.html.erb
<h1> All events</h1> <ul class="list-group">
<% for event in @events %>
<li class="list-group-item"><%= link_to event.artist, "/events/#{event.id}" %></li>
<% end %> </ul>
<div class="btn btn-primary">
<%= link_to 'Nowe ogłoszenie', new_event_path, :style => 'color: white; text-decoration: none'%>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<p id="komunikat"><%= flash[:komunikat] %></p>

<h1>Event</h1>

<p>
  <strong>Artist:</strong>
  <%= @event.artist %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Price low:</strong>
  <%= @event.price_low %>
</p>

<p>
  <strong>Price high:</strong>
  <%= @event.price_high %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.event_date %>
</p>

<%= render "tickets_list", tickets: @event.tickets %>

<%if current_user != nil%>
<%= render "new_ticket", ticket: Ticket.new(:event_id=>@event.id) %>
<% end%>


<%= link_to 'Back', events_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bilety</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-dark bg-primary" >
  <a class="navbar-brand" href="/events" style="color: white">Events</a>
  <a class="navbar-brand" href="/tickets" style="color: white">Tickets</a>
  <p class="navbar-text pull-right"> <% if user_signed_in? %>
Logged in as <strong><%= current_user.email %></strong>.
  <% if current_user.isAdmin%>
  ADMIN
  <% end%>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link ', :style => 'color: white; text-decoration: none' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link', :style => 'color: white; text-decoration: none'%>
<% else %>
<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link', :style => 'color: white'%> | <%= link_to "Login", new_user_session_path, :class => 'navbar-link', :style => 'color: white; text-decoration: none' %>
<% end %> </p>
</nav>
   

  <% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
 <p class="alert alert-danger"><%= alert %></p> <% end %>
    <%= yield %>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
        <div class="col-sm-12  mx-auto p-4">
<div class="form-group" style="margin-left: 100px; margin-right: 100px">
<% if ticket.id == nil%>
<h1>New Ticket</h1>
<% end%>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :class => "form-control"%>
  </div>

  <div class="field">
    <%= form.label :seat_id_seq %>
    <%= form.text_field :seat_id_seq, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :email_address %>
    <%= form.text_field :email_address, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.hidden_field :event_id, :value => ticket.event_id%>
  </div>

<%= form.select(:event_id, options_for_select(Event.all.map { |c| [c.artist + ' ' + c.event_date.to_s, c.id]}, ticket.event_id), {}, {class: "form-control", id: "dropdownMenuButton"}) %>


<div class="field">
    <%= form.hidden_field :user_id, :value => current_user.id%>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
  
  </div>
  </div>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Tickets</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Seat id seq</th>
      <th>Address</th>
      <th>Price</th>
      <th>Phone</th>
      <th>Email address</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.phone %></td>
        <td><%= ticket.email_address %></td>
        <td><%= ticket.user.email %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= button_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if current_user.nil?%>
<%= link_to 'New Ticket', new_ticket_path %>
<% end%>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Seat id seq:</strong>
  <%= @ticket.seat_id_seq %>
</p>

<p>
  <strong>Address:</strong>
  <%= @ticket.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @ticket.phone %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @ticket.email_address %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>